condor_submit jobs/ftm_test_beam_0001/job.job -name ettore
condor_submit jobs/ftm_test_beam_0002/job.job -name ettore
condor_submit jobs/ftm_test_beam_0003/job.job -name ettore
condor_submit jobs/ftm_test_beam_0004/job.job -name ettore
condor_submit jobs/ftm_test_beam_0005/job.job -name ettore
condor_submit jobs/ftm_test_beam_0006/job.job -name ettore
condor_submit jobs/ftm_test_beam_0007/job.job -name ettore
condor_submit jobs/ftm_test_beam_0008/job.job -name ettore
condor_submit jobs/ftm_test_beam_0009/job.job -name ettore
