condor_submit jobs/ftm_test_beam_0001/job.job -name ettore
condor_submit jobs/ftm_test_beam_0002/job.job -name ettore
condor_submit jobs/ftm_test_beam_0003/job.job -name ettore
condor_submit jobs/ftm_test_beam_0004/job.job -name ettore
condor_submit jobs/ftm_test_beam_0005/job.job -name ettore
condor_submit jobs/ftm_test_beam_0006/job.job -name ettore
condor_submit jobs/ftm_test_beam_0007/job.job -name ettore
condor_submit jobs/ftm_test_beam_0008/job.job -name ettore
condor_submit jobs/ftm_test_beam_0009/job.job -name ettore
condor_submit jobs/ftm_test_beam_0010/job.job -name ettore
condor_submit jobs/ftm_test_beam_0011/job.job -name ettore
condor_submit jobs/ftm_test_beam_0012/job.job -name ettore
condor_submit jobs/ftm_test_beam_0013/job.job -name ettore
condor_submit jobs/ftm_test_beam_0014/job.job -name ettore
condor_submit jobs/ftm_test_beam_0015/job.job -name ettore
condor_submit jobs/ftm_test_beam_0016/job.job -name ettore
condor_submit jobs/ftm_test_beam_0017/job.job -name ettore
condor_submit jobs/ftm_test_beam_0018/job.job -name ettore
condor_submit jobs/ftm_test_beam_0019/job.job -name ettore
condor_submit jobs/ftm_test_beam_0020/job.job -name ettore
condor_submit jobs/ftm_test_beam_0021/job.job -name ettore
condor_submit jobs/ftm_test_beam_0022/job.job -name ettore
condor_submit jobs/ftm_test_beam_0023/job.job -name ettore
condor_submit jobs/ftm_test_beam_0024/job.job -name ettore
condor_submit jobs/ftm_test_beam_0025/job.job -name ettore
condor_submit jobs/ftm_test_beam_0026/job.job -name ettore
condor_submit jobs/ftm_test_beam_0027/job.job -name ettore
condor_submit jobs/ftm_test_beam_0028/job.job -name ettore
condor_submit jobs/ftm_test_beam_0029/job.job -name ettore
condor_submit jobs/ftm_test_beam_0030/job.job -name ettore
condor_submit jobs/ftm_test_beam_0031/job.job -name ettore
condor_submit jobs/ftm_test_beam_0032/job.job -name ettore
condor_submit jobs/ftm_test_beam_0033/job.job -name ettore
condor_submit jobs/ftm_test_beam_0034/job.job -name ettore
condor_submit jobs/ftm_test_beam_0035/job.job -name ettore
condor_submit jobs/ftm_test_beam_0036/job.job -name ettore
condor_submit jobs/ftm_test_beam_0037/job.job -name ettore
condor_submit jobs/ftm_test_beam_0038/job.job -name ettore
condor_submit jobs/ftm_test_beam_0039/job.job -name ettore
condor_submit jobs/ftm_test_beam_0040/job.job -name ettore
condor_submit jobs/ftm_test_beam_0041/job.job -name ettore
condor_submit jobs/ftm_test_beam_0042/job.job -name ettore
condor_submit jobs/ftm_test_beam_0043/job.job -name ettore
condor_submit jobs/ftm_test_beam_0044/job.job -name ettore
condor_submit jobs/ftm_test_beam_0045/job.job -name ettore
condor_submit jobs/ftm_test_beam_0046/job.job -name ettore
condor_submit jobs/ftm_test_beam_0047/job.job -name ettore
condor_submit jobs/ftm_test_beam_0048/job.job -name ettore
condor_submit jobs/ftm_test_beam_0049/job.job -name ettore
condor_submit jobs/ftm_test_beam_0050/job.job -name ettore
condor_submit jobs/ftm_test_beam_0051/job.job -name ettore
condor_submit jobs/ftm_test_beam_0052/job.job -name ettore
condor_submit jobs/ftm_test_beam_0053/job.job -name ettore
condor_submit jobs/ftm_test_beam_0054/job.job -name ettore
condor_submit jobs/ftm_test_beam_0055/job.job -name ettore
condor_submit jobs/ftm_test_beam_0056/job.job -name ettore
condor_submit jobs/ftm_test_beam_0057/job.job -name ettore
condor_submit jobs/ftm_test_beam_0058/job.job -name ettore
condor_submit jobs/ftm_test_beam_0059/job.job -name ettore
condor_submit jobs/ftm_test_beam_0060/job.job -name ettore
condor_submit jobs/ftm_test_beam_0061/job.job -name ettore
condor_submit jobs/ftm_test_beam_0062/job.job -name ettore
condor_submit jobs/ftm_test_beam_0063/job.job -name ettore
condor_submit jobs/ftm_test_beam_0064/job.job -name ettore
condor_submit jobs/ftm_test_beam_0065/job.job -name ettore
condor_submit jobs/ftm_test_beam_0066/job.job -name ettore
condor_submit jobs/ftm_test_beam_0067/job.job -name ettore
condor_submit jobs/ftm_test_beam_0068/job.job -name ettore
condor_submit jobs/ftm_test_beam_0069/job.job -name ettore
condor_submit jobs/ftm_test_beam_0070/job.job -name ettore
condor_submit jobs/ftm_test_beam_0071/job.job -name ettore
condor_submit jobs/ftm_test_beam_0072/job.job -name ettore
condor_submit jobs/ftm_test_beam_0073/job.job -name ettore
condor_submit jobs/ftm_test_beam_0074/job.job -name ettore
condor_submit jobs/ftm_test_beam_0075/job.job -name ettore
condor_submit jobs/ftm_test_beam_0076/job.job -name ettore
condor_submit jobs/ftm_test_beam_0077/job.job -name ettore
condor_submit jobs/ftm_test_beam_0078/job.job -name ettore
condor_submit jobs/ftm_test_beam_0079/job.job -name ettore
condor_submit jobs/ftm_test_beam_0080/job.job -name ettore
condor_submit jobs/ftm_test_beam_0081/job.job -name ettore
condor_submit jobs/ftm_test_beam_0082/job.job -name ettore
condor_submit jobs/ftm_test_beam_0083/job.job -name ettore
condor_submit jobs/ftm_test_beam_0084/job.job -name ettore
condor_submit jobs/ftm_test_beam_0085/job.job -name ettore
condor_submit jobs/ftm_test_beam_0086/job.job -name ettore
condor_submit jobs/ftm_test_beam_0087/job.job -name ettore
condor_submit jobs/ftm_test_beam_0088/job.job -name ettore
condor_submit jobs/ftm_test_beam_0089/job.job -name ettore
condor_submit jobs/ftm_test_beam_0090/job.job -name ettore
condor_submit jobs/ftm_test_beam_0091/job.job -name ettore
condor_submit jobs/ftm_test_beam_0092/job.job -name ettore
condor_submit jobs/ftm_test_beam_0093/job.job -name ettore
condor_submit jobs/ftm_test_beam_0094/job.job -name ettore
condor_submit jobs/ftm_test_beam_0095/job.job -name ettore
condor_submit jobs/ftm_test_beam_0096/job.job -name ettore
condor_submit jobs/ftm_test_beam_0097/job.job -name ettore
condor_submit jobs/ftm_test_beam_0098/job.job -name ettore
condor_submit jobs/ftm_test_beam_0099/job.job -name ettore
condor_submit jobs/ftm_test_beam_0100/job.job -name ettore
